[build]
builder = "Nixpacks"
buildCommand = "cd backend-node && npm install --production && cd ../frontend-vue3 && npm install --omit=dev && npm run build"

[deploy]
startCommand = "cd backend-node && node app.js"

[env]
PORT = "3003"
NODE_ENV = "production"